### ISSUE TITLE
hello_world.sh tests do not pass

### ISSUE THREAD

**Issue by kenden** [exercism/xbash#9]
The tests for hello_word.sh do not pass.
```
 $ bats hello_world_test.sh 
 ✗ When given no name, it should greet the world!
   (in test file hello_world_test.sh, line 4)
     `[ "$status" -eq 0 ]' failed
 ✗ When given "Alice" it should greet Alice!
   (in test file hello_world_test.sh, line 11)
     `[ "$status" -eq 0 ]' failed
 ✗ When given "Bob" it should greet Bob!
   (in test file hello_world_test.sh, line 18)
     `[ "$status" -eq 0 ]' failed
 ✗ When given an empty string it should have a space and punctuation, though admittedly this is strange.
   (in test file hello_world_test.sh, line 25)
     `[ "$status" -eq 0 ]' failed
 ✗ When given "Alice and Bob" it greets them both
   (in test file hello_world_test.sh, line 32)
     `[ "$status" -eq 0 ]' failed

5 tests, 5 failures
```
The content of hello_world.sh comes from 
https://github.com/exercism/xbash/blob/master/hello-world/example.sh
and looks correct:
 ```
$ env bash hello_world.sh 
Hello, World!
$ env bash hello_world.sh Alice
Hello, Alice!
$ env bash hello_world.sh Bob
Hello, Bob!
$ env bash hello_world.sh ""
Hello, !
$ env bash hello_world.sh Alice and Bob
Hello, Alice and Bob!
```

**Versions of software used:**
```
$ bats --version
Bats 0.4.0

$ uname -a
Linux machinename 0 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ env bash --version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
```

**Comment by kenden** [comment]
The issue is that my ```hello_world.sh``` is not executable.
I made a PR to fix this. The code is correct, it's a burden to have to ```chmod +x hello_word.sh``` and confusing when nothing points to this issue in the very first excercise.

**Comment by adelcambre** [comment]
@kytrinyx Yeah! 

@kenden The change seems sane to me, I'll give it a once over and make any comments over there.

**Comment by kenden** [comment]
@adelcambre Thanks for merging.
How does ```exercism fetch bash hello-world``` get the last version (from master)?

**Comment by kytrinyx** [comment]
You'd have to delete the old files locally, the exercism cli doesn't overwrite existing files.

**Comment by kenden** [comment]
Verified fixed. Closing.

**Comment by ninrod** [comment]
my hello_world.sh is not passing. scripts being executable or not does not make a difference. here's my implementation: 

```sh
set -o errexit
set -o nounset

main() {
  echo "Hello, world!"
  return 0
}

main "$@"
```

running bats hello_world_test.sh gives this: 

```txt
hello-world ➜ bats hello_world_test.sh 
 ✗ Say Hi!
   (in test file hello_world_test.sh, line 6)
     `[ "$status" -eq 0 ]' failed

1 test, 1 failure
hello-world ➜ 
```

What is happening?

**Comment by sjwarner-bp** [comment]
Hi @ninrod - if you double-check the test:

```
#!/usr/bin/env bats

@test "Say Hi!" {
  run bash hello_world.sh

  [ "$status" -eq 0 ]
  [ "$output" = "Hello, World!" ]
}
```

Your output isn't *quite* correct... `Hello, world!` isn't quite the same as `Hello, World!`

Does that make sense? :slightly_smiling_face: 

For future reference, there is a [Gitter room](https://gitter.im/exercism/bash) for these kind of questions too :slightly_smiling_face:

**Comment by ninrod** [comment]
Jesus \o/. Good catch! thanks!
Well, I have to say that I would expect bats to give me at least a diff highlighting the differences. Am I right?

**Comment by kenden** [comment]
@ninrod I believe this is documented in this feature request for bats: 
https://github.com/bats-core/bats-core/issues/77

**Comment by ninrod** [comment]
excelent. but then, we could ask the user to install said assertion library for more ergomics, right?

**Comment by sjwarner-bp** [comment]
Might be worth seeing what the response is on the `bats-core` issue before we action anything over here (last comment was only 3 days ago!)

**Comment by CivZero** [comment]
I know this is almost a year old and I'm sorry for bringing this back up again, but I can't seem to get this script to run. Here is what I've written. 

`
#!/usr/bin/env bash


set -o errexit
set -o nounset

main() {

  input=$1

  echo "Hello, World!"
}

main "$@"
`
Please help. I'm losing my mind trying to figure out what I did wrong. I made sure that the output is exact, that the bats version is updated and that the .sh's are executable.

**Comment by kytrinyx** [comment]
@CivZero Would you mind opening an issue in http://github.com/exercism/exercism/issues? I'm not sure this will get seen by anyone who is currently active on the bash track and could help since this issue is closed and very old.

**Comment by NobbZ** [comment]
The same has been asked in #272, I've left my reply there.

Luckily `bash` repository is on my watch list and I get notified about discussions here.
